export const INIT_PROJECTS = 'INIT_PROJECTS';
export const INIT_TASKS = 'INIT_TASKS';
export const CLEAR_PROJECTS_AND_TASKS = 'CLEAR_PROJECTS_AND_TASKS';
export const FB_ERROR = 'FB_ERROR';
export const SUCCESS = 'SUCCESS';
export const FB_ERROR_DISMISS = 'FB_ERROR_DISMISS';
export const SUCCESS_DISMISS = 'SUCCESS_DISMISS';
export const SUCCESS_DISAPPEAR = 'SUCCESS_DISAPPEAR';
